### ISSUE TITLE
[Bug] Inconsistent Behavior for World Upload

### ISSUE THREAD

**Issue by FlamedDogo99** [FlamedDogo99/EaglerMobile#11]
**Describe the Bug**
Uploading a vanilla Minecraft world either leads to a crash, or the file uploader won’t dismiss itself
**Steps to Reproduce**
1. Start EaglerCraft client with EaglerMobile userscript
2. Tap the screen to start the client, and wait for it to load
3. Navigate to the main menu by hitting done when presented with the edit profile menu
4. Select single player, create new world, import world, and then upload the world file attached below
5. Observe a crash, or the file uploader not disappearing

**Additional Information**
My user agent: 
```
Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1
```
Eagler Mobile version: `2.4`

Screenshot of the file uplaoder not being dismissed after selecting a file:
![IMG_0602](https://github.com/FlamedDogo99/EaglerMobile/assets/96555444/3c0655c1-2f11-463c-a711-c43cf8ab0725)

The vanilla Minecraft world used in the screenshot:
[20 MORE Doors in 100 Seconds! - Copy.zip](https://github.com/user-attachments/files/15710182/20.MORE.Doors.in.100.Seconds.-.Copy.zip)

**Comment by RealPlurr** [comment]
Btw it happens only in IOS if someone interested ^^^

**Comment by colbychittenden** [comment]
i thought you used android? but yeah this is a really annoying bug

**Comment by FlamedDogo99** [comment]
**If anyone can recreate this issue on other devices and browsers, please leave a comment with the relevant information.** (I will be testing it across Safari, Chrome and Firefox on MacOS later tonight.)
Currently I just don’t have enough information to troubleshoot this one, especially the crashes.

**Comment by FlamedDogo99** [comment]
I just realized that the createElement function is indiscriminately grabbing any input element, which is a really dumb problem. This should be a fairly easy fix. I’ll correct it tomorrow.

**Comment by PlurrYT-Kolama** [comment]
> i thought you used android? but yeah this is a really annoying bug

i mean yes but i mean it doesnt happens on android
