### ISSUE TITLE
[Bug] Chrome for iOS tries to save or open the buttons in a new tab

### ISSUE THREAD

**Issue by lax1dude** [FlamedDogo99/EaglerMobile#15]
**Describe the Bug**

I know I'm a dumbass for installing Google's browser on my phone but it looks like this is unusable due to one of it's special features.

In order to play with this effectively I need to press and hold the buttons, but when I do that chrome tries to save the image or open it in a new tab. It looks like Google made saving the `background-image` of an element a feature in their app.

You can probably stop this from happening by canceling certain events although I'm not exactly sure.

![image](https://github.com/FlamedDogo99/EaglerMobile/assets/23693545/ed2c0657-5ccb-457d-8606-153d807c0fbf)

**Steps to Reproduce**

Google Chrome on iOS, loaded via `<script>` tag

**Comment by FlamedDogo99** [comment]
I’ll have to see how chrome handles everything, but it should be fairly easy to fix.
It will probably either be
```css
.mobileControl {
  pointer-events: none;
}
```

or

```js
button.addEventListener(“contextmenu”, (e) => {
  e.preventDefault();
}
```

**Comment by FlamedDogo99** [comment]
Setting `pointer-events` to `none` completely prevents you from pressing buttons 🤦

I need to do some more research

**Comment by FlamedDogo99** [comment]
This should be fixed in #20, although I did only test it with Chrome on Xcode Simulator, so holler if it hasn't been resolved

**Comment by lax1dude** [comment]
I tried it on my phone and it worked, no more context menu, although it is still possible to select the buttons as text.

**Comment by FlamedDogo99** [comment]
I’ll apply the same change the buttons next release.
