### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by nooblittlepuke** [FlamedDogo99/EaglerMobile#38]
Hey!
So i have a few bugs to report that are all on iOS devices.
anyway here are the bugs i report in this comment.
----------------------
1. Cant install profile
-- The profile of m.eaglercraft.com cannot be installed for some odd reason. I have a iPhone 14 and with the iOS 18 update.
-----------------------------
2. Keyboard on iOS doesnt work after using the chat
--Some servers in the game has to verify user right? Or lets just say you got cheats on, and you want something with the /give command on Mobile, The Keyboard button doesn't work after you type and enter. After you use it, it just thinks the whole page is a text and selects the Arrow keys.
----------------------
Anyways thats all the bugs i have to say. If you see this by any chance please fix these bugs. Other Mobile players would Love this fix.

If your associated with M.Eaglercraft.com
Please send me the discord link as the link of it is expired.

**Comment by nooblittlepuke** [comment]
so like are yall finna fix the profile download for the eaglercraft

**Comment by FlamedDogo99** [comment]
Closed due to duplicate issue. Please note that this extension is not developed by the eaglercraft developers. In fact, I was quite surprised to see it being used on the official website.
