### ISSUE TITLE
Half of features listed made

### ISSUE THREAD

**Issue by irv77** [FlamedDogo99/EaglerMobile#5]
Hey I didn't make a pull request but I did make a github repo of the code updated. Here is what has been done to it:

- Chat bug fix
- Pause button not always showing
- UI positioning change
- Hold crouch lock
- Separate sprint button
- Strafe forward left/right added
- Custom icons

_(It's in my profile)_

**Comment by FlamedDogo99** [comment]
Thanks for creating an issue. I will work on directly implementing:
- [ ] Your updated UI 
- [ ] F3 button
- [ ] Chat bug

And I will be rewriting and implementing:
- [ ] Crouch lock (Which I think I might just change it to a toggle)
- [ ] Sprint button (Which I’ll also probably make into a toggle)
- [ ] Strafe (Which will activate based on touching and dragging either left or right like PE)

My only issue with your suggestions is not displaying the exit button when pointerlock isn’t called. To the best of my knowledge, the exit key is the only way to get out of chest, furnace and crafting table GUI. Once I can directly get the game state, this will not be an issue.

Thanks!

**Comment by irv77** [comment]
My bad didn't look into the other block gui's to see if they had exits!

**Comment by FlamedDogo99** [comment]
You’re completely fine, I had the same thing originally. I’m currently working on cleaning up the current iteration of the mobile script, and then I’ll start adding your suggestions.
Out of curiosity, do you know if the mobile controls normally have separate icons for when they are pressed?

**Comment by irv77** [comment]
On newer versions when they are pressed they have a pressed icon look (different colors and sometimes design). Got my code to be updated with yours also.

![comparison](https://github.com/FlamedDogo99/EaglerMobile/assets/137123638/bf338957-7b51-4870-8957-c3c726809d21)

**Comment by FlamedDogo99** [comment]
Yeah I have no idea what to do with crafting. Until I can figure out how to directly inject JavaScript into the client, there’s not much we can really do

**Comment by FlamedDogo99** [comment]
Next update is going to be updating the UI. I’m about halfway through redrawing the icons to match the current new PE design.

**Comment by irv77** [comment]
Okay, you could also just use the PE new textures. You can just download the base resource pack and find it in the files.

https://github.com/Mojang/bedrock-samples/releases
