### ISSUE TITLE
[Bug] Keyboard issue on Android mobile devices 

### ISSUE THREAD

**Issue by RealPlurr** [FlamedDogo99/EaglerMobile#7]
**Describe the Bug**
Keyboard doesn't work correctly (or at all) on android phone (redmi 8). Wont type in chat or and wont type in username field.

**Steps to Reproduce**
Start launcher, click keyboard button try to type and see it works broken or dont work at all.

**Additional Information**
Browser google and chrome. Latest version available from google play market. Phone redmi 8 using google keyboard and android version 10, MIUI 12.5.3 (stable version)

**Comment by colbychittenden** [comment]
idk if it will work i was the one who added the keyboard button and i only have iOS so i only tested it there

**Comment by RealPlurr** [comment]
Like keyboard opens but with it also whole game moves down, and secondly it wont even type so idk. ChatGPT says that it technically muss work but it doesn't.

**Comment by colbychittenden** [comment]
moves the game down? if its moving the game out of the way for the keyboard then thats probably built into the os/browser.

**Comment by RealPlurr** [comment]
Yeah but it also makes like idk white gap between keyboard and game it can be also bug of this js feature idk but anyways it isnt such critical bug the most critical that it wont type at all

**Comment by colbychittenden** [comment]
But the keyboard opens right?

**Comment by RealPlurr** [comment]
It opens keyboard but it wont type leme attach photos

**Comment by RealPlurr** [comment]
![Screenshot_2024-06-02-17-03-24-378_com android chrome](https://github.com/FlamedDogo99/EaglerMobile/assets/93705241/25425c7a-d909-49d5-be8a-a56bb15da919)
![Screenshot_2024-06-02-17-03-15-836_com android chrome](https://github.com/FlamedDogo99/EaglerMobile/assets/93705241/d534f109-17d7-43d5-b10f-ec074c902b03)

**Comment by RealPlurr** [comment]
Also new bug button goes off screen before it wasn't happening and I typed "Bello" and it didn't wrote as you see

**Comment by FlamedDogo99** [comment]
I have several ideas I can try, but support is limited since we currently don’t have any android devices to test with.
Several ideas:
[ ] Test if changing input opacity from 0 changes anything
[ ] Add `type="text"` to input element
Also, this may be an issue with the Chrome browser on android (see [https://github.com/nosir/cleave.js/issues/147](https://github.com/nosir/cleave.js/issues/147))

**Comment by colbychittenden** [comment]
I mean we could test in android studio just running a browser

**Comment by RealPlurr** [comment]
Okay, I hope y'all will be able to fix it. By the way you can emulate android using BlueStackX or smth

**Comment by RealPlurr** [comment]
> I mean we could test in android studio just running a browser

Also good option

**Comment by FlamedDogo99** [comment]
I just quickly added both ideas, holler if it makes a difference

**Comment by RealPlurr** [comment]
Leme test it rq

**Comment by RealPlurr** [comment]
![Screenshot_2024-06-02-17-19-42-033_com android chrome](https://github.com/FlamedDogo99/EaglerMobile/assets/93705241/2469d02a-f8aa-4b1f-839e-ee61d8900613)

Now buttons are a bit out of their places

And Now I can't close keyboard using button it keeps appearing after closing it using < or button

**Comment by RealPlurr** [comment]
Oh wait forgot to rotate phone my bad leme test it rotated

**Comment by colbychittenden** [comment]
and the button doesn't close it it only opens it

**Comment by FlamedDogo99** [comment]
I need to do some more research on this. I’ll get back to you.

**Comment by RealPlurr** [comment]
Ok so. It still bugged and buttons are out of screen. Secondly its impossible now to close keyboard beacuse it loops opens. Thirdly it wont type like it was. White gaps became smaller but still exist

**Comment by RealPlurr** [comment]
> and the button doesn't close it it only opens it

Then we need add for mobile android devices close button beacuse it loop opens it

**Comment by colbychittenden** [comment]
Well by what i have tested its impossible to close the keyboard with js so idk

**Comment by RealPlurr** [comment]
Then uh need unloop it somehow, anyways but it still wont type its also critical bug now there is 2 critical bugs

**Comment by colbychittenden** [comment]
okay...

**Comment by RealPlurr** [comment]
I think now its kinda chrome issue fully..

**Comment by colbychittenden** [comment]
let me test it on chrome on ios and see if i get the same issues

**Comment by colbychittenden** [comment]
no i dont get the issue but its probably because apple makes google use webkit on ios chrome but on android im guessing it uses chromium?

**Comment by RealPlurr** [comment]
Yeah it definitely uses Chromium ig. Anyways it still happens probably even android bug idk. The fact keyboard is hella buggy is fact

**Comment by colbychittenden** [comment]
try using another browser that has another engine like firefox and see if it happens there

**Comment by RealPlurr** [comment]
Same issue

**Comment by colbychittenden** [comment]
hmmmmm

**Comment by RealPlurr** [comment]
No clue it muss be fixed somehow... there is a lot more android users than iOS users so yeah

**Comment by colbychittenden** [comment]
yea

**Comment by FlamedDogo99** [comment]
Alright I have a solution but it will take me some time to fix regardless.
1) Looping open keyboard
This flaw appears to have been here since the button was added. I’ll have to keep track of the keyboard state and toggle between open and closed, which is fairly easy to implement.
2) Android key presses
It appears that we can’t trust android to dispatch the proper key events. Eagler needs `key`, `keyCode`, and `which`. My current idea is to completely eliminate android’s keyboard events. Instead, we read changes to the hidden keyboard input and dispatch the event programmatically ourselves. Here’s the general outline of what needs to change
- [ ] override key event completely to include an extra `don’t ignore` flag.
- [ ] Update all script key events to include the `don’t ignore` flag
- This allows us to disregard any keyboard inputs
- [ ] add an event listener to the keyboard input that has an onchange event listener.
- [ ] When the event listener fires, we read the new value from the input, pass it through to our normal keyEvent function, and then clear the input
- We also need to allow there to be a character within the input so we can detect the delete key press through the length of the input decreasing.

This would eliminate the need for constantly implementing changes to jump through each devices requirements for reading the key events, and feels fairly straightforward to implement.

**Comment by colbychittenden** [comment]
Yeah I would have made the keyboard button do that and track the state but it just worked for me when clicking the done button on the top of the keyboard it would be fine so that's why I didn't ![image](https://github.com/FlamedDogo99/EaglerMobile/assets/96893162/a9c9f480-e6cf-4834-b653-6de0e0f33415)

**Comment by PlurrYT-Kolama** [comment]
android doesn't have such button

**Comment by colbychittenden** [comment]
i fixed the looping check my pull request

**Comment by colbychittenden** [comment]
oh and completely off topic but i've found by using shadow client i can get at least 30 fps so i think thats the next thing to try to make it automatically optimize the settings

**Comment by RealPlurr** [comment]
completely off topic thing was useless because with this client im getting 190+ fps on pc and 40-60+ fps on mobile

**Comment by colbychittenden** [comment]
well good for you i was just saying from my personal experience

**Comment by FlamedDogo99** [comment]
Y’all keep it on topic in the issues. I can open up discussions if you really want to do that

**Comment by colbychittenden** [comment]
okay sorry but can you?

**Comment by RealPlurr** [comment]
Anyways lets move to issue. Any progress on fix?

**Comment by colbychittenden** [comment]
no not really

**Comment by colbychittenden** [comment]
(for me)

**Comment by FlamedDogo99** [comment]
Actually, I could use all of your help. If anyone has an android device, could they go to https://w3c.github.io/uievents/tools/key-event-viewer.html and type “e”, and post a screenshot of the result here? I’m close to a solution but I want to make sure it will work.

**Comment by colbychittenden** [comment]
i dont have an android device but here's it in bluestacks ![image](https://github.com/FlamedDogo99/EaglerMobile/assets/96893162/feab5ab3-c492-41b2-9c98-a20351a7c526)

**Comment by RealPlurr** [comment]
Here is android device
![Uploading Screenshot_2024-06-03-17-25-56-698_com.android.chrome.jpg…]()

**Comment by RealPlurr** [comment]
![Uploading Screenshot_2024-06-03-17-25-56-698_com.android.chrome.jpg…]()

**Comment by RealPlurr** [comment]
![Screenshot_2024-06-03-17-25-56-698_com android chrome](https://github.com/FlamedDogo99/EaglerMobile/assets/93705241/559872a5-0cdd-440c-b492-434c61d1ecd6)

**Comment by PlurrYT-Kolama** [comment]
any updates?

**Comment by FlamedDogo99** [comment]
Oh wow, that’s not good. Most of  your UIEvents are undefined, and that makes this extremely hard to work with. This is what it ideally should be closer to:
![IMG_0594](https://github.com/FlamedDogo99/EaglerMobile/assets/96555444/fd74fec5-1c1c-4243-836b-362c8f662cf5)

**Comment by PlurrYT-Kolama** [comment]
uh then its android issue

**Comment by PlurrYT-Kolama** [comment]
we kinda cant do anything about that so kinda this project is broken for android

**Comment by FlamedDogo99** [comment]
If someone can figure out how to detect android devices, I’ll start working on the bloated solution.

**Comment by PlurrYT-Kolama** [comment]
ik how to do it leme send u code rq

**Comment by PlurrYT-Kolama** [comment]
function getDeviceType() {
  var userAgent = navigator.userAgent || navigator.vendor;

  if (/android/i.test(userAgent)) {
    return "Android";
  }

  if (/iPad|iPhone|iPod/.test(userAgent) && !window.MSStream) {
    return "iOS";
  }

  if (/Win|Mac|Linux/i.test(userAgent)) {
    return "PC";
  }

  return "Unknown";
}

console.log(getDeviceType());



this muss work i hope

**Comment by PlurrYT-Kolama** [comment]
yeah but it still wont fix for everyone

**Comment by PlurrYT-Kolama** [comment]
> > If someone can figure out how to detect android devices, I’ll start working on the bloated solution.
> 
> If android doesn’t support the basic Keyboard Events, it means that any project that detects key presses will be broken. Looking at other forums, some android users have recommended this: https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard&hl=en

anyways need try to fix that issue and not be like "other projects"

**Comment by colbychittenden** [comment]
Just do it via the user agent

**Comment by PlurrYT-Kolama** [comment]
???? you mean about detection of android yeah can use that too

**Comment by colbychittenden** [comment]
To detect android

**Comment by PlurrYT-Kolama** [comment]
yeah i literally gave code above how to do that

**Comment by PlurrYT-Kolama** [comment]
function getDeviceType() {
var userAgent = navigator.userAgent || navigator.vendor;

if (/android/i.test(userAgent)) {
return "Android";
}

if (/iPad|iPhone|iPod/.test(userAgent) && !window.MSStream) {
return "iOS";
}

if (/Win|Mac|Linux/i.test(userAgent)) {
return "PC";
}

return "Unknown";
}

console.log(getDeviceType());

**Comment by colbychittenden** [comment]
Oh sorry I didn’t see

**Comment by PlurrYT-Kolama** [comment]
by the way why we cant use keydown or input? It will probably fix bug

**Comment by FlamedDogo99** [comment]
When android dispatches keydown events, everything is either undefined or zero regardless of what key is pressed. I’ll have to use input which will make us lose a lot of events such as shift keys

**Comment by PlurrYT-Kolama** [comment]
leme see i saw on stackoverflow translator of keydown thingy for android

**Comment by PlurrYT-Kolama** [comment]
https://stackoverflow.com/questions/30743490/capture-keys-typed-on-android-virtual-keyboard-using-javascript <- here check this out

**Comment by FlamedDogo99** [comment]
I think I managed to get it working. Can someone check [https://github.com/FlamedDogo99/EaglerMobile/tree/keyboard-fix](https://github.com/FlamedDogo99/EaglerMobile/tree/keyboard-fix) that has an android device and report back?

**Comment by colbychittenden** [comment]
Idk if it works on android but I know it messes it up on iOS so you might need to add a detection to use the old method for iOS and the new one for android

**Comment by FlamedDogo99** [comment]
> Idk if it works on android but I know it messes it up on iOS so you might need to add a detection to use the old method for iOS and the new one for android

Before I merge I'll definitely do that. Right now I'm just wanting to make sure I'm not wasting my time with this attempt.

**Comment by colbychittenden** [comment]
Yea and that new commit you just did fixed it but now you can clearly see the input in the corner

**Comment by PlurrYT-Kolama** [comment]
leme test it on android

**Comment by FlamedDogo99** [comment]
Yeah, I just hid the input again, we'll see what happens

**Comment by PlurrYT-Kolama** [comment]
write here when u fixed and ill test it

**Comment by FlamedDogo99** [comment]
Alright it should (in theory) work. Currently the space key creates a "_" but that can be fixed after we make sure this works.

**Comment by PlurrYT-Kolama** [comment]
backspace works strange i need open and close keyboard to do single backspace

**Comment by PlurrYT-Kolama** [comment]
testing ...  but typing works fine looks like just backspace broke but other stuff fixed

**Comment by PlurrYT-Kolama** [comment]
i got error after setting name leme ss it and send from realplurr

**Comment by RealPlurr** [comment]
![Screenshot_2024-06-03-22-33-07-544_com android chrome](https://github.com/FlamedDogo99/EaglerMobile/assets/93705241/11af4217-b6b0-486f-ac75-ed811aa5dd50)
![Screenshot_2024-06-03-22-33-12-535_com android chrome](https://github.com/FlamedDogo99/EaglerMobile/assets/93705241/eacead2e-b2fa-4fc2-a994-c9492acdca6d)

**Comment by RealPlurr** [comment]
Aka, it fixed keyboard but backspace works strange (can be used only one time other wise need reopen keyboard), and this update broke server list

**Comment by FlamedDogo99** [comment]
I have no idea how you have a browser that doesn’t support ES3, but I guess I can I can try and add a polyfill method for apply and call functions. How long has is been since you’ve updated your phone?

**Comment by FlamedDogo99** [comment]
Alright I added polyfill functions for apply and call, if someone can test [https://raw.githubusercontent.com/FlamedDogo99/EaglerMobile/keyboard-fix/eaglermobile.user.js](https://raw.githubusercontent.com/FlamedDogo99/EaglerMobile/keyboard-fix/eaglermobile.user.js), I would be greatly appreciative

**Comment by RealPlurr** [comment]
> I have no idea how you have a browser that doesn’t support ES3, but I guess I can I can try and add a polyfill method for apply and call functions. How long has is been since you’ve updated your phone?


Like im on stable release of MIUI, means its release of MIUM (redmi/Xiaomi OS based on android)  what has got nearly everyone who isnt in beta testing programm

**Comment by RealPlurr** [comment]
> Alright I added polyfill functions for apply and call, if someone can test https://raw.githubusercontent.com/FlamedDogo99/EaglerMobile/keyboard-fix/eaglermobile.user.js, I would be greatly appreciative
> 
> > Aka, it fixed keyboard but backspace works strange (can be used only one time other wise need reopen keyboard), and this update broke server list
> 
> For some reason the added function that ignores keyboard events was causing that issue for you, although I have no clue why

 Bug with keyboard backspace still exist

**Comment by RealPlurr** [comment]
![Screenshot_2024-06-04-07-18-48-908_com android chrome](https://github.com/FlamedDogo99/EaglerMobile/assets/93705241/70019861-6bb6-4055-906d-c27fb9d07bf0)

**Comment by PlurrYT-Kolama** [comment]
can someone else fix this then?

**Comment by FlamedDogo99** [comment]
Someone else is welcome to try. If they can figure out why your specific device doesn’t handle `EventTarget.prototype.addEventListener` the same as most other devices, they’d probably be able to help. However without this function (or something similar) you’ll not be able to type in inputs (which is needed because your device just doesn’t work with keydown events), and even if you could type, I’m pretty sure you’d get repeated key presses randomly.

**Comment by FlamedDogo99** [comment]
Alright, this is my last attempt on this particular solution for the android keyboard problems. It works on Safari, macOS chrome, and even Orion, so if it throws an error on your device, I’m out of ideas.
[https://raw.githubusercontent.com/FlamedDogo99/EaglerMobile/keyboard-fix/eaglermobile.user.js](https://raw.githubusercontent.com/FlamedDogo99/EaglerMobile/keyboard-fix/eaglermobile.user.js)

**Comment by RealPlurr** [comment]
Testing...

**Comment by RealPlurr** [comment]
![Screenshot_2024-06-06-07-13-08-515_com android chrome](https://github.com/FlamedDogo99/EaglerMobile/assets/93705241/6e06c1c7-066d-4e5a-b058-80335a34099e)
I think its beacuse android doesn't understand "fn"? All other errots contained fn and here to.

**Comment by RealPlurr** [comment]
It throws error in multiplayer tab mostly

**Comment by FlamedDogo99** [comment]
Wait it does this without you even typing?

**Comment by RealPlurr** [comment]
Hi yeah managed to recreate it in other pages too, anyways yeah it crashes without any interaction i guess i explained really bad. My bad, I'll wait for a fix and sorry that I explained without big ammount of details :)

**Comment by FlamedDogo99** [comment]
I think I fixed it. Currently anything besides a-z, A-Z, 0-9, and the delete key will probably not work, but if there’s no crashes that will be easy to fix.

**Comment by FlamedDogo99** [comment]
I think there’s a syntax error in there somewhere, so if it looks broken it’s my fault. I’ll fix it this afternoon

**Comment by RealPlurr** [comment]
Okay testing updated version

**Comment by RealPlurr** [comment]
![Screenshot_2024-06-07-07-56-11-702_com android chrome](https://github.com/FlamedDogo99/EaglerMobile/assets/93705241/5adc1b21-62a0-4dd4-ab78-ae4e27f32181)
New issue, typing works fine in profils page but when it goes to server (chat) you cant select chat line and / or type there

**Comment by RealPlurr** [comment]
But yeah it fixed error and I managed to join server ^^^

**Comment by FlamedDogo99** [comment]
> But yeah it fixed error and I managed to join server ^^^

That’s a step in the right direction then.

> New issue: typing works fine in profile page but when it goes to server (chat) you can’t select chat line or type there

I’ll look at it closer Tom

**Comment by FlamedDogo99** [comment]
Out of curiosity, when you go to chat is there a blinking "_" that displays where you would be typing?

**Comment by RealPlurr** [comment]
Hello im back I'll test in minutes

**Comment by RealPlurr** [comment]
Wait where is latest code just it shows yesterday at all js codes if you mean at all version no its not blinking _ if you about new version idk where it is located at

**Comment by FlamedDogo99** [comment]
I'm going to close this issue and open a new one specifically for not being able to type in chat on android, since we have solved the problem with not being able to dispatch valid keyboard events.

**Comment by FlamedDogo99** [comment]
I just realized that this is not fully fixed with some Android devices, although I think got it working on the `input-fix` branch.
